DROP TABLE IF EXISTS FILMS, FILM_GENRES, FRIENDSHIPS, LIKES, USERS, FILM_DIRECTOR, RATES_MPA, GENRES,
    DIRECTORS, REVIEWS, REVIEW_RATINGS, EVENTS;

CREATE TABLE IF NOT EXISTS RATES_MPA
(
    mpa_id   tinyint PRIMARY KEY,
    mpa_name varchar(50)
);

CREATE TABLE IF NOT EXISTS GENRES
(
    genre_id int PRIMARY KEY,
    genre    varchar(100)
);

CREATE TABLE IF NOT EXISTS USERS
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(100),
    login    varchar(100),
    name     varchar(100),
    birthday date
);

CREATE TABLE IF NOT EXISTS FILMS
(
    film_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50),
    description varchar(200),
    releaseDate date,
    duration    int,
    rate_id     int REFERENCES RATES_MPA (mpa_id)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    film_id  bigint REFERENCES FILMS (film_id) ON DELETE CASCADE,
    genre_id int REFERENCES GENRES (genre_id),
    CONSTRAINT film_genres_pk PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS LIKES
(
    user_id bigint REFERENCES USERS (user_id) ON DELETE CASCADE,
    film_id bigint REFERENCES FILMS (film_id) ON DELETE CASCADE,
    CONSTRAINT likes_pk PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS FRIENDSHIPS
(
    user_id     bigint REFERENCES USERS (user_id) ON DELETE CASCADE,
    friend_id   bigint REFERENCES USERS (user_id) ON DELETE CASCADE,
    is_approved boolean,
    CONSTRAINT friendships_pk PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS REVIEWS
(
    review_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     varchar(500),
    is_positive boolean,
    user_id     bigint REFERENCES USERS (user_id) ON DELETE CASCADE,
    film_id     bigint REFERENCES FILMS (film_id) ON DELETE CASCADE,
    useful  bigint
);

CREATE TABLE IF NOT EXISTS REVIEW_RATINGS
(
    review_id bigint REFERENCES REVIEWS (review_id) ON DELETE CASCADE,
    user_id bigint REFERENCES USERS (user_id) ON DELETE CASCADE,
    liked boolean,
    PRIMARY KEY (review_id, user_id, liked)
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    event_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp  date,
    user_id    bigint REFERENCES USERS (user_id) ON DELETE CASCADE,
    event_type varchar(10),
    operation  varchar(10),
    entity_id  bigint
);

CREATE TABLE IF NOT EXISTS DIRECTORS
(
    director_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name varchar(100)
);

CREATE TABLE IF NOT EXISTS FILM_DIRECTOR
(
    film_id     bigint REFERENCES FILMS (film_id) ON DELETE CASCADE,
    director_id bigint REFERENCES DIRECTORS (director_id) ON DELETE CASCADE,
    CONSTRAINT film_director_pk PRIMARY KEY (film_id, director_id)
);